application: rgxtest
version: 2
runtime: python27
api_version: 1
threadsafe: True

inbound_services:
- mail

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /_ah/mail/.+
  script: app.inmail.views.handle
  login: admin
# configured in config.py as well
- url: /static
  static_dir: static
# main app handler (uses app.routes to get main routes)
- url: /.*
  script: app.handler
